import { User, Vendor, WeeklyVisit, Complaint, DailyReport, TrainingCourse, AuditLog } from './types';

export const DEMO_USERS: User[] = [
  {
    id: 'u-1',
    email: 'admin@mamihubs.com',
    name: 'Chloe Henderson',
    role: 'admin',
    region: 'Global Hub',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    phone: '+1 (555) 019-2831',
  },
  {
    id: 'u-2',
    email: 'sarah@mamihubs.com',
    name: 'Sarah Jenkins',
    role: 'supervisor',
    region: 'East Hub',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    phone: '+1 (555) 012-4411',
  },
  {
    id: 'u-3',
    email: 'marcus@mamihubs.com',
    name: 'Marcus Vance',
    role: 'supervisor',
    region: 'Central Hub',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    phone: '+1 (555) 018-9922',
  },
  {
    id: 'u-4',
    email: 'david@mamihubs.com',
    name: 'David Cole',
    role: 'field_personnel',
    region: 'East Hub',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    phone: '+1 (555) 014-5566',
    assignedSupervisorId: 'u-2',
  },
  {
    id: 'u-5',
    email: 'maria@mamihubs.com',
    name: 'Maria Santos',
    role: 'field_personnel',
    region: 'Central Hub',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
    phone: '+1 (555) 011-8899',
    assignedSupervisorId: 'u-3',
  },
  {
    id: 'u-6',
    email: 'jessica@mamihubs.com',
    name: 'Jessica Chen',
    role: 'field_personnel',
    region: 'East Hub',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    phone: '+1 (555) 017-3344',
    assignedSupervisorId: 'u-2',
  }
];

export const DEMO_VENDORS: Vendor[] = [
  {
    id: 'v-1',
    name: 'Mami & Me Organics',
    ownerName: 'Clara Oswald',
    phone: '+1 (555) 123-4567',
    email: 'clara@mamimeorganics.com',
    hubRegion: 'East Hub',
    category: 'Supermarkets',
    city: 'Lagos',
    registeredDate: '2026-06-01',
    onboardingStep: 6,
    checklist: {
      registered: true,
      profileCompleted: true,
      firstProductUploaded: true,
      min10ProductsUploaded: true,
      firstOrderReceived: true,
      firstOrderFulfilled: true,
    },
    products: [
      { id: 'p-1', name: 'Organic Mashed Apple & Pear pureé', price: 6.99, category: 'Organic Purees', createdAt: '2026-06-03', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-2', name: 'Plum & Spelt Toddler Teething Rusks', price: 5.49, category: 'Teething & Snacks', createdAt: '2026-06-03', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-3', name: 'Gentle Chamomile Nighttime Tea blend', price: 8.99, category: 'Motherhood Blends', createdAt: '2026-06-04', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-101', name: 'Sweet Potato & Ancient Grain Pot', price: 4.80, category: 'Organic Purees', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-102', name: 'Butternut Squash & Chia Bowl', price: 4.80, category: 'Organic Purees', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-103', name: 'Gluten-Free Oats porridge', price: 7.20, category: 'Teething & Snacks', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-104', name: 'Banana & Quinoa puree cup', price: 3.50, category: 'Organic Purees', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-105', name: 'Probiotic Strawberry bites pack', price: 6.50, category: 'Teething & Snacks', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-106', name: 'Mami Chamomile Calm oil', price: 12.99, category: 'Motherhood Blends', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-107', name: 'Super Berry teething melt', price: 6.50, category: 'Teething & Snacks', createdAt: '2026-06-05', status: 'approved', isOrganicOrFamilyCertified: true }
    ],
    ordersCount: 14,
    inactiveDays: 1,
    qualityStatus: 'approved',
    fieldOfficerId: 'u-4', // David Cole
    lastVisitDate: '2026-06-12',
  },
  {
    id: 'v-2',
    name: 'Little Sprouts Apparel',
    ownerName: 'Elena Rostova',
    phone: '+1 (555) 987-6543',
    email: 'elena@littlesprouts.com',
    hubRegion: 'East Hub',
    category: 'Fashion stores',
    city: 'Abuja',
    registeredDate: '2026-06-05',
    onboardingStep: 3,
    checklist: {
      registered: true,
      profileCompleted: true,
      firstProductUploaded: true,
      min10ProductsUploaded: false,
      firstOrderReceived: false,
      firstOrderFulfilled: false,
    },
    products: [
      { id: 'p-4', name: 'Bamboo Soft Knit Maternity Wrap Cloak', price: 49.99, category: 'Maternity Clothes', createdAt: '2026-06-08', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-5', name: 'Organic Cotton Newborn Romper (Sage)', price: 24.99, category: 'Baby Clothes', createdAt: '2026-06-09', status: 'pending_review', isOrganicOrFamilyCertified: true }
    ],
    ordersCount: 0,
    inactiveDays: 8,
    qualityStatus: 'pending',
    fieldOfficerId: 'u-4', // David Cole
    lastVisitDate: '2026-06-10',
  },
  {
    id: 'v-3',
    name: 'NurtureNest Toys',
    ownerName: 'Aiden Ramirez',
    phone: '+1 (555) 753-1590',
    email: 'aiden@nurturenest.com',
    hubRegion: 'Central Hub',
    category: 'Furniture dealers',
    city: 'Port Harcourt',
    registeredDate: '2026-06-10',
    onboardingStep: 5,
    checklist: {
      registered: true,
      profileCompleted: true,
      firstProductUploaded: true,
      min10ProductsUploaded: true,
      firstOrderReceived: true,
      firstOrderFulfilled: false,
    },
    products: [
      { id: 'p-6', name: 'Heirloom Beechwood Stacking Ark', price: 34.00, category: 'Wooden Toys', createdAt: '2026-06-11', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-7', name: 'Montessori Sensory Felt Texture Cards', price: 18.00, category: 'Sensory Cards', createdAt: '2026-06-11', status: 'approved', isOrganicOrFamilyCertified: false },
      { id: 'p-201', name: 'Wooden Peg Balancing Board', price: 28.00, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-202', name: 'Pastel Rainbow Rainbow Arch Set', price: 32.00, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-203', name: 'Baby Forest Walk Mobile rattle', price: 15.00, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-204', name: 'Shapes and Holes Sorting Chest', price: 22.00, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-205', name: 'Animal Sound Cylinder Shakers', price: 19.50, category: 'Sensory Cards', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-206', name: 'Silicone Ring Teether pastel pack', price: 14.00, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-207', name: 'Organic Hemp Toddler backpack', price: 38.00, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-208', name: 'Toddler Nesting Cups tower', price: 16.99, category: 'Wooden Toys', createdAt: '2026-06-12', status: 'approved', isOrganicOrFamilyCertified: true }
    ],
    ordersCount: 1,
    inactiveDays: 3,
    qualityStatus: 'approved',
    fieldOfficerId: 'u-5', // Maria Santos
    lastVisitDate: '2026-06-12',
  },
  {
    id: 'v-4',
    name: 'Bloom Nursing & Wellness',
    ownerName: 'Dr. Jean Miller',
    phone: '+1 (555) 246-8101',
    email: 'info@bloom nursing.com',
    hubRegion: 'East Hub',
    category: 'Pharmacies',
    city: 'Enugu',
    registeredDate: '2026-06-14',
    onboardingStep: 2,
    checklist: {
      registered: true,
      profileCompleted: true,
      firstProductUploaded: false,
      min10ProductsUploaded: false,
      firstOrderReceived: false,
      firstOrderFulfilled: false,
    },
    products: [],
    ordersCount: 0,
    inactiveDays: 5,
    qualityStatus: 'pending',
    fieldOfficerId: 'u-6', // Jessica Chen
  },
  {
    id: 'v-5',
    name: 'EarthMami Baby Herbal',
    ownerName: 'Nisha Vyas',
    phone: '+1 (555) 369-1215',
    email: 'nisha@earthmamiwellness.com',
    hubRegion: 'Central Hub',
    category: 'Cosmetics stores',
    city: 'Aba',
    registeredDate: '2026-05-20',
    onboardingStep: 4,
    checklist: {
      registered: true,
      profileCompleted: true,
      firstProductUploaded: true,
      min10ProductsUploaded: true,
      firstOrderReceived: false,
      firstOrderFulfilled: false,
    },
    products: [
      { id: 'p-8', name: 'Whipped Shea & Cocoa Nappy Balm', price: 14.99, category: 'Balms & Lotions', createdAt: '2026-05-22', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-9', name: 'Sweet Almond Calendula Baby Massage Oil', price: 16.99, category: 'Balms & Lotions', createdAt: '2026-05-22', status: 'rejected', isOrganicOrFamilyCertified: true },
      { id: 'p-20', name: 'Organic Soothing Lavender Soap bar', price: 6.99, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-21', name: 'Hydrating Stretch Mark Butter', price: 22.00, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-22', name: 'Herbal Sitz Bath infusion tea', price: 18.00, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-23', name: 'Cooling leg balm for mama', price: 14.50, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-24', name: 'Tender nipple ointment organic', price: 15.00, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-25', name: 'Zinc oxide natural barrier cream', price: 11.90, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-26', name: 'Baby hair wash chamomile tearless', price: 13.00, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true },
      { id: 'p-27', name: 'Soothing oatmeal milk bath powder', price: 17.50, category: 'Organic Cosmetics', createdAt: '2026-05-25', status: 'approved', isOrganicOrFamilyCertified: true }
    ],
    ordersCount: 0,
    inactiveDays: 20, // Track as high high inactive vendor
    qualityStatus: 'action_required',
    fieldOfficerId: 'u-5', // Maria Santos
    lastVisitDate: '2026-06-03',
  },
  {
    id: 'v-6',
    name: 'Nest & Nap Co.',
    ownerName: 'Sarah Ferguson',
    phone: '+1 (555) 444-1122',
    email: 'sarah@nestandnap.com',
    hubRegion: 'East Hub',
    category: 'Fashion stores',
    city: 'Onitsha',
    registeredDate: '2026-06-18',
    onboardingStep: 1,
    checklist: {
      registered: true,
      profileCompleted: false,
      firstProductUploaded: false,
      min10ProductsUploaded: false,
      firstOrderReceived: false,
      firstOrderFulfilled: false,
    },
    products: [],
    ordersCount: 0,
    inactiveDays: 1,
    qualityStatus: 'pending',
    fieldOfficerId: 'u-4', // David Cole
  }
];

export const DEMO_VISITS: WeeklyVisit[] = [
  {
    id: 'w-1',
    vendorId: 'v-1',
    vendorName: 'Mami & Me Organics',
    supervisorId: 'u-2',
    supervisorName: 'Sarah Jenkins',
    date: '2026-06-12',
    durationMinutes: 45,
    notes: 'Superb operations. Inspected new batch of Apple Purees. Quality standards perfect. Discussed supply bottlenecks.',
    checklistReviewed: true,
    gpsLocation: {
      lat: 40.7128,
      lng: -74.0060,
      address: 'East River Hub Outlet #12, Brooklyn',
    }
  },
  {
    id: 'w-2',
    vendorId: 'v-2',
    vendorName: 'Little Sprouts Apparel',
    supervisorId: 'u-2',
    supervisorName: 'Sarah Jenkins',
    date: '2026-06-10',
    durationMinutes: 30,
    notes: 'Elena requested assistance in uploading batch files. Guided her on high-resolution text requirements. Scheduled a follow-up through David Cole.',
    checklistReviewed: true,
    gpsLocation: {
      lat: 40.7306,
      lng: -73.9352,
      address: 'Greenpoint Creator Space, Brooklyn',
    }
  },
  {
    id: 'w-3',
    vendorId: 'v-5',
    vendorName: 'EarthMami Baby Herbal',
    supervisorId: 'u-3',
    supervisorName: 'Marcus Vance',
    date: '2026-06-03',
    durationMinutes: 60,
    notes: 'Urgent site audit for organic certification. Found label discrepancies on the Sweet Almond Massage Oil. Opened a quality status amendment ticket.',
    checklistReviewed: true,
    gpsLocation: {
      lat: 41.8781,
      lng: -87.6298,
      address: 'Mils Road Organic Warehousing, Chicago',
    }
  }
];

export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: 'c-1',
    vendorId: 'v-2',
    vendorName: 'Little Sprouts Apparel',
    title: 'Image Upload Bug in Merchant Portal',
    description: 'We have tried uploading premium linen swatches for the bamboo knit lines but keep receiving error code 413. This is stalling our product uploading checkpoint.',
    category: 'product_listing',
    createdAt: '2026-06-15T09:30:00Z',
    status: 'open',
    severity: 'medium',
  },
  {
    id: 'c-2',
    vendorId: 'v-5',
    vendorName: 'EarthMami Baby Herbal',
    title: 'Unresponsive Onboarding Support regarding labels',
    description: 'We are waiting for validation on our organic certificates for Calendula massage oil. It has been 6 days since we uploaded files, and our store remains partially flagged as Action Required.',
    category: 'unresponsive_officer',
    createdAt: '2026-06-12T14:15:00Z',
    status: 'in_progress',
    severity: 'high',
  },
  {
    id: 'c-3',
    vendorId: 'v-3',
    vendorName: 'NurtureNest Toys',
    title: 'Bank Verification Delays',
    description: 'Our routing number verification took 4 days. Resolved in collaboration with payment squad.',
    category: 'payouts',
    createdAt: '2026-06-05T11:00:00Z',
    status: 'resolved',
    severity: 'low',
    resolutionText: 'Onboarding supervisor manual override verification. Accounts cleared, bank payout terminal configured.',
    resolvedAt: '2026-06-06T16:00:00Z',
    resolvedBy: 'u-3',
  }
];

export const DEMO_REPORTS: DailyReport[] = [
  {
    id: 'r-1',
    fieldOfficerId: 'u-4',
    fieldOfficerName: 'David Cole',
    date: '2026-06-18',
    vendorsOnboardedCount: 1,
    stepsCompletedCount: 4,
    summary: 'Visited Clara Oswald (Mami & Me Organics) for order fulfillment check. Visited Nest & Nap Co. to initiate onboarding. They registered successfully today.',
    challenges: 'Nest & Nap owner has a busy newborn nurse schedule, hard to hold focus for long setups.',
    status: 'pending_review',
  },
  {
    id: 'r-2',
    fieldOfficerId: 'u-5',
    fieldOfficerName: 'Maria Santos',
    date: '2026-06-18',
    vendorsOnboardedCount: 0,
    stepsCompletedCount: 2,
    summary: 'Assisted Aiden Ramirez (NurtureNest Toys) to log their first mock order. Verified Montessori sensory cards compliance.',
    challenges: 'None. Aiden is very self-guided.',
    status: 'reviewed',
    supervisorNotes: 'Excellent work assisting Aiden. Keep driving the remaining checklist items!',
  },
  {
    id: 'r-3',
    fieldOfficerId: 'u-6',
    fieldOfficerName: 'Jessica Chen',
    date: '2026-06-17',
    vendorsOnboardedCount: 0,
    stepsCompletedCount: 1,
    summary: 'Completed Bloom Nursing physical location assessment. Verified certificates.',
    challenges: 'Internet connectivity at the clinic was very poor, making remote app sync slow.',
    status: 'reviewed',
    supervisorNotes: 'Noted on clinic internet issues. You can use standard field logs off-line and sync later.',
  }
];

export const DEMO_COURSES: TrainingCourse[] = [
  {
    id: 't-1',
    title: 'High-Touch Micro-Merchant Empathy',
    description: 'Learn the emotional peaks and valleys of home-based mompreneurs. This course teaches how field officers should build high trust, accommodate family schedules, and handle childcare disruptions during onboarding setup.',
    category: 'Customer Success',
    durationMinutes: 45,
    completedByFieldOfficers: ['u-4', 'u-5'],
  },
  {
    id: 't-2',
    title: 'Marketplace Organic & Family Standards Audit',
    description: 'Deep dive into Market Stormer compliance requirements. Review organic certification labels, toxic-free baby product clearances, and home kitchen sanitation standards for small scale suppliers.',
    category: 'Product Quality',
    durationMinutes: 60,
    completedByFieldOfficers: ['u-4'],
  },
  {
    id: 't-3',
    title: 'Instructing First-Order Fulfilment',
    description: 'Best-practices tutorial for training vendors on packaging, sustainable bubble wraps, shipping labels, and printing. Ensures a magical first unboxing experience.',
    category: 'Digital Sales',
    durationMinutes: 30,
    completedByFieldOfficers: ['u-5', 'u-6'],
  },
  {
    id: 't-4',
    title: 'Safeguarding Merchant Bank Data & PII',
    description: 'Field officer guidelines to prevent collecting or viewing raw credit credentials or writing routing passwords offline. Ensures strict adherence to privacy compliance.',
    category: 'Code of Conduct',
    durationMinutes: 40,
    completedByFieldOfficers: [],
  }
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    timestamp: '2026-06-18T17:15:00Z',
    userId: 'u-4',
    userName: 'David Cole',
    userRole: 'field_personnel',
    action: 'REGISTER_VENDOR',
    details: 'Completed registration for vendor: Nest & Nap Co.',
  },
  {
    id: 'log-2',
    timestamp: '2026-06-18T15:30:00Z',
    userId: 'u-2',
    userName: 'Sarah Jenkins',
    userRole: 'supervisor',
    action: 'RESOLVE_COMPLAINT',
    details: 'Reviewed status and flagged EarthMami organic label discrepancy in investigation.',
  },
  {
    id: 'log-3',
    timestamp: '2026-06-18T10:00:00Z',
    userId: 'u-1',
    userName: 'Chloe Henderson',
    userRole: 'admin',
    action: 'SYSTEM_AUDIT',
    details: 'Inspected East Region and Central Region consolidated metrics; approved field training allocation.',
  }
];
